name: Generate Fantasy AI Image

on:
  schedule:
    # 每 5 分鐘觸發一次（理論上）
    - cron: '*/15 * * * *'
  workflow_dispatch:  # 可手動觸發

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢出程式碼
      - name: Check out code
        uses: actions/checkout@v4

      # 2. 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 安裝套件
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. 執行圖片產生腳本
      - name: Run image generation script
        run: python generate_image.py

      # 5. 設定 Git 提交者資訊
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 6. 自動 commit 並推送圖片回 main 分支
      - name: Commit and push generated images
        run: |
          git add images/
          git commit -m "chore: add generated image on $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push origin HEAD:main
